name: eh_lib
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: paddy <xupaddy@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  requests: ^2.0.1
  html: ^0.14.0+2

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
